---
title: "Project_2_Histone_Modifications_BG"
author: "Florence Marti"
date: "2025-06-11"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/EpiGen_Project_Valerie_Florence/Histone Modifications BG")

suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(GenomicRanges)
  library(epiwraps)
  library(rtracklayer)
  library(ggplot2)
  library(magick)
  library(R.utils) 
  library(MASS)
  library(TxDb.Hsapiens.UCSC.hg38.knownGene)
  library(org.Hs.eg.db)
  library(AnnotationDbi)
})
```

Import Histone Modification Peak Data
```{r setup, include=TRUE}
options(timeout = 12000)


# Monocytes
H3K4me3_M0 <- rtracklayer::import("H3K4me3_M0_BC17.bed", format = "BED")
H3K27ac_M0 <- rtracklayer::import("H3K27ac_M0_BC17.bed", format = "BED")
H3K4me1_M0 <- rtracklayer::import("H3K4me1_M0_BC17.bed", format = "BED")

# Macrophages
H3K4me3_MF <- rtracklayer::import("H3K4me3_MF_BC17.bed", format = "BED")
H3K27ac_MF <- rtracklayer::import("H3K27ac_MF_BC17.bed", format = "BED")
H3K4me1_MF <- rtracklayer::import("H3K4me1_MF_BC17.bed", format = "BED")

# BG primed macrophages
H3K4me3_BG <- rtracklayer::import("H3K4me3_BG_BC17.bed", format = "BED")
H3K27ac_BG <- rtracklayer::import("H3K27ac_BG_BC17.bed", format = "BED")
H3K4me1_BG <- rtracklayer::import("H3K4me1_BG_BC17.bed", format = "BED")

```

Define Pro- and Anti-inflammatory Transcription Factors
```{r setup, include=TRUE}
pro_inflammatory <- c("RELA", "RELB", "REL", "NFKB1", "NFKB2", "FOS", "JUN", "STAT1", "STAT2", 
                     "STAT3", "STAT4", "STAT5A", "STAT5B", "IRF5", "IRF8", "IRF1",
                     "IRF3", "CEBPA", "CEBPD", "SPI1", "KLF6", "HIF1A", "NOTCH1", "BRD4")

anti_inflammatory <- c("STAT6", "PPARG", "KLF4", "MAFB", "IRF4", "KDM6B", "MYC", "NR4A1", 
                      "BCL6", "CREB1", "RXRA", "FOXO1", "SP1", "GATA3", "SMAD3")

entrez_ids_pro <- mapIds(org.Hs.eg.db, keys = pro_inflammatory,
                        column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")
entrez_ids_anti <- mapIds(org.Hs.eg.db, keys = anti_inflammatory,
                         column = "ENTREZID", keytype = "SYMBOL", multiVals = "first")

entrez_ids_pro_df <- data.frame(HGNC_Symbol = names(entrez_ids_pro), 
                               Entrez_ID = as.character(entrez_ids_pro), 
                               stringsAsFactors = FALSE)

entrez_ids_anti_df <- data.frame(HGNC_Symbol = names(entrez_ids_anti),
                                Entrez_ID = as.character(entrez_ids_anti),
                                stringsAsFactors = FALSE)

entrez_ids_pro_df
entrez_ids_anti_df
```



Load Gene Annotations and Define Promoters


```{r setup, include=TRUE}
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
genes_txdb <- genes(txdb)
```


```{r setup, include=TRUE}
# Remove NAs and subset genes by Entrez IDs
entrez_pro_ids <- na.omit(as.character(entrez_ids_pro_df$Entrez_ID))
entrez_anti_ids <- na.omit(as.character(entrez_ids_anti_df$Entrez_ID))

selected_pro_genes <- genes_txdb[names(genes_txdb) %in% entrez_pro_ids]
selected_anti_genes <- genes_txdb[names(genes_txdb) %in% entrez_anti_ids]

# Promoters ± 2kb around TSS
tss_regions_pro <- promoters(selected_pro_genes, upstream = 2000, downstream = 2000)
tss_regions_anti <- promoters(selected_anti_genes, upstream = 2000, downstream = 2000)
```



Count Overlaps of Histone Modifications with Promoters


```{r setup, include=TRUE}
me3_overlap_M0_pro <- countOverlaps(tss_regions_pro, H3K4me3_M0)
me3_overlap_M0_anti <- countOverlaps(tss_regions_anti, H3K4me3_M0)

me3_overlap_MF_pro <- countOverlaps(tss_regions_pro, H3K4me3_MF)
me3_overlap_MF_anti <- countOverlaps(tss_regions_anti, H3K4me3_MF)

me3_overlap_BG_pro <- countOverlaps(tss_regions_pro, H3K4me3_BG)
me3_overlap_BG_anti <- countOverlaps(tss_regions_anti, H3K4me3_BG)

ac_overlap_M0_pro <- countOverlaps(tss_regions_pro, H3K27ac_M0)
ac_overlap_M0_anti <- countOverlaps(tss_regions_anti, H3K27ac_M0)

ac_overlap_MF_pro <- countOverlaps(tss_regions_pro, H3K27ac_MF)
ac_overlap_MF_anti <- countOverlaps(tss_regions_anti, H3K27ac_MF)

ac_overlap_BG_pro <- countOverlaps(tss_regions_pro, H3K27ac_BG)
ac_overlap_BG_anti <- countOverlaps(tss_regions_anti, H3K27ac_BG)

me1_overlap_M0_pro <- countOverlaps(tss_regions_pro, H3K4me1_M0)
me1_overlap_M0_anti <- countOverlaps(tss_regions_anti, H3K4me1_M0)

me1_overlap_MF_pro <- countOverlaps(tss_regions_pro, H3K4me1_MF)
me1_overlap_MF_anti <- countOverlaps(tss_regions_anti, H3K4me1_MF)

me1_overlap_BG_pro <- countOverlaps(tss_regions_pro, H3K4me1_BG)
me1_overlap_BG_anti <- countOverlaps(tss_regions_anti, H3K4me1_BG)
```


```{r setup, include=TRUE}
dataframe_pro <- data.frame(
  TF= pro_inflammatory, 
  M0_H3K4me3 = me3_overlap_M0_pro, M0_H3K27ac = ac_overlap_M0_pro , M0_H3K4me1 = me1_overlap_M0_pro , 
  MF_H3K4me3 = me3_overlap_MF_pro, MF_H3K27ac = ac_overlap_MF_pro , MF_H3K4me1 = me1_overlap_MF_pro ,
  BG_H3K4me3 = me3_overlap_BG_pro , BG_H3K27ac = ac_overlap_BG_pro, BG_H3K4me1 = me1_overlap_BG_pro
)
dataframe_pro

dataframe_anti <- data.frame(
  TF= anti_inflammatory, 
  M0_H3K4me3 = me3_overlap_M0_anti, M0_H3K27ac = ac_overlap_M0_anti , M0_H3K4me1 = me1_overlap_M0_anti , 
  MF_H3K4me3 = me3_overlap_MF_anti, MF_H3K27ac = ac_overlap_MF_anti , MF_H3K4me1 = me1_overlap_MF_anti ,
  BG_H3K4me3 = me3_overlap_BG_anti , BG_H3K27ac = ac_overlap_BG_anti, BG_H3K4me1 = me1_overlap_BG_anti
)
dataframe_anti


```

Define Chromatin States Function and Apply
```{r setup, include=TRUE}
assign_state <- function(me3, ac, me1) {
  if (me3 & ac & !me1) return("Active promoter")
  if (!me3 & ac & me1) return("Enhancer")
  if (me3 & !ac & !me1) return("Poised promoter")
  if (!me3 & ac & !me1) return("Unusual activation")
  if (!me3 & !ac & !me1) return("Unmarked")
  return("Other")
}
```


```{r setup, include=TRUE}
# Pro-inflammatory
dataframe_pro$ChromatinState_M0 <- mapply(assign_state,
                                          dataframe_pro$M0_H3K4me3,
                                          dataframe_pro$M0_H3K27ac,
                                          dataframe_pro$M0_H3K4me1)

dataframe_pro$ChromatinState_MF <- mapply(assign_state,
                                         dataframe_pro$MF_H3K4me3,
                                         dataframe_pro$MF_H3K27ac,
                                         dataframe_pro$MF_H3K4me1)

dataframe_pro$ChromatinState_BG <- mapply(assign_state,
                                         dataframe_pro$BG_H3K4me3,
                                         dataframe_pro$BG_H3K27ac,
                                         dataframe_pro$BG_H3K4me1)

# Anti-inflammatory
dataframe_anti$ChromatinState_M0 <- mapply(assign_state,
                                           dataframe_anti$M0_H3K4me3,
                                           dataframe_anti$M0_H3K27ac,
                                           dataframe_anti$M0_H3K4me1)

dataframe_anti$ChromatinState_MF <- mapply(assign_state,
                                          dataframe_anti$MF_H3K4me3,
                                          dataframe_anti$MF_H3K27ac,
                                          dataframe_anti$MF_H3K4me1)

dataframe_anti$ChromatinState_BG <- mapply(assign_state,
                                          dataframe_anti$BG_H3K4me3,
                                          dataframe_anti$BG_H3K27ac,
                                          dataframe_anti$BG_H3K4me1)
Summary and Visualization
```


```{r}
Copy
Edit
library(reshape2)
library(ggplot2)

pro_long <- reshape2::melt(dataframe_pro, id.vars = c("TF", "ChromatinState_M0", "ChromatinState_MF", "ChromatinState_BG"),
                           measure.vars = c("M0_H3K4me3", "M0_H3K27ac", "M0_H3K4me1",
                                            "MF_H3K4me3", "MF_H3K27ac", "MF_H3K4me1",
                                            "BG_H3K4me3", "BG_H3K27ac", "BG_H3K4me1"),
                           variable.name = "Condition_Mod", value.name = "Overlap")

ggplot(pro_long, aes(x = TF, y = Overlap, fill = Condition_Mod)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Histone Modification Overlaps at Pro-inflammatory TF Promoters",
       y = "Overlap Counts", x = "Transcription Factor")
```
